(require <asteroids_util_general>)
(require <asteroids_util_math>)

(define synth::javax.sound.midi.Synthesizer (javax.sound.midi.MidiSystem:getSynthesizer))
(synth:open)
(define rec::javax.sound.midi.Receiver (synth:getReceiver))

(define-macro (sm x) `(static-field javax.sound.midi.ShortMessage ',x))
(define-macro (make-note a b c)
    (define-gensyms x)
    `(returning (,x (javax.sound.midi.ShortMessage))
        (invoke ,x 'setMessage ,a ,b ,c)
    )
)
(define-macro (emit a b c)
   `(invoke rec 'send (make-note ,a ,b ,c) -1)
)
(define instr 000)
(define pitch 127)
(with-min-ms-per-iteration 50
    (emit (sm NOTE_OFF) pitch 0)
    (printf "instrument %s; pitch %s\n" instr pitch)
    (emit (sm PROGRAM_CHANGE) instr 0)
    (inc! pitch 4)
    (inplace! (wrap 40 60) pitch)
    (inc! instr 7)
    (inplace! (wrap 0 127) instr)
    (emit (sm NOTE_ON) pitch #x7f)
)
