(define GL2 javax.media.opengl.GL2)
(define printf java.lang.System:out:printf)

(define jf (javax.swing.JFrame))
(jf:setSize 640 480)
(jf:setResizable #f)
(jf:setDefaultCloseOperation javax.swing.JFrame:EXIT_ON_CLOSE)
(define glcanv (javax.media.opengl.awt.GLCanvas))
(define (randomByte)::byte (* 255 (java.lang.Math:random)))
(define (randomColor gl2::GL2) (gl2:glColor3b (randomByte) (randomByte) (randomByte)))
(define (drawTriangle gl2::GL2)
    ;(printf "in drawTriangle\n")
    (gl2:glClear gl2:GL_COLOR_BUFFER_BIT)
    (gl2:glBegin gl2:GL_TRIANGLES)
    (for-each (lambda (xy)
        (randomColor gl2)
        (apply gl2:glVertex2d xy)
    ) '((0 0) (1 0) (0 1)))
    (gl2:glEnd)
)
(glcanv:addGLEventListener (object (javax.media.opengl.GLEventListener)
    ((*init*) #!void)
    ((display drawable) (drawTriangle ((drawable:getGL):getGL2)))
    ((init drawable) #!void)
    ((dispose drawable) #!void)
    ((reshape drawable x y w h) #!void)
))
(jf:add glcanv)
(jf:setVisible #t)
(define anim (com.jogamp.opengl.util.FPSAnimator glcanv 5))
(anim:start)
